title: "Mohammad Rasouli Koohi"
email: mohammadrasooli.koohi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "mohammad-rasouli.github.io"
# You only need to define your social links here and no need to edit the footer.html
social:
  twitter_username: wrussell1999
  github_username:  wrussell1999
  linkedin_username: wrussell1999


sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
resume: /assets/resume.pdf
